version: "3"

tasks:
  migrate:
    aliases:
      - migrate
    desc: "Migrate databases"
    cmds:
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  
  runapp:
    aliases:
      - run
    desc: "Run app"
    cmds:
      - go run ./cmd/sso/main.go --config=./config/local.yaml